name: json_object_mapper
description: Simple and easy way to map Objects to/from Map and JSON with Web support.
version: 1.0.0
homepage: https://github.com/gmpassos/json_object_mapper

environment:
  sdk: '>=2.6.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
