name: json_object_mapper
description: A simple and easy way to map Objects from JSON and to Map with support for Dart Native and Dart Web.
version: 2.0.0
homepage: https://github.com/gmpassos/json_object_mapper

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  swiss_knife: ^3.0.0
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  #test_coverage: ^0.4.3
