name: json_object_mapper
description: A simple and easy way to map Objects from JSON and to Map with support for Dart Native and Dart Web.
version: 1.1.0
homepage: https://github.com/gmpassos/json_object_mapper

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  swiss_knife: ^2.5.9
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
